### ISSUE TITLE
Code Failed to Comple

### ISSUE THREAD

**Issue by smeschke** [ianboru/juggle-tracker-js#1]
I downloaded the repository, used _npm install_ then _npm start_. The React app Failed to Load, giving the following error message: 

> Failed to compile
> 
> ./src/store.js
> Module not found: Can't resolve 'mobx' in '/home/stephen/Desktop/juggle-tracker-js-master/src'
> 
> This error occurred during the build time and cannot be dismissed._

**Comment by ianboru** [comment]
I see I forgot to commit my package.json changes. I just added them so it should work now with npm install. Sorry about that!
