### ISSUE TITLE
Color segmentation for white objects.

### ISSUE THREAD

**Issue by smeschke** [ianboru/juggle-tracker-js#3]
Color segmentation for the color white has eluded me. I find that it is easiest to segment bright colors like green, blue, or purple. White presents several challenges. First, HSV color space (the one that I am most comfortable with) is not the best colorspace for segmenting white. Second, white balls will often be juggled in front of a white background. White-on-white makes color segmentation impossible.

One possible solution, is to avoid using colorspaces at all. If the white objects are the brightest thing in the frame, thresholding can be used to find the white objects.

Another possible solution is to have the user alter the environment so that the props are the brightest thing in the frame. This is pretty much impossible to do with white balls, but it is really easy to do with glow in the dark balls.

**Comment by ianboru** [comment]
I'm ok pausing on that for now. Since I had some success in RGB we can wait to see if an RGB toggle helps.
